### PR TITLE
Task sorter v0.0.2

### PR DESCRIPTION
**Pull request by dwertheimer**
Sort tasks in a note by priority (e.g. !, !!, !!! -- the more exclamations, the higher the priority -- also works with todo.txt (A), (B) etc.)
My personal workflow: Sweep tasks with /sw7 and then sort tasks with /ts (see my /sw7 pull request also)
Ignores indents for now, but once I understand more about @EduardMe's heading-indent thinking, I can get it back in there.

Need to work on the @context and #hashtag sorting next.

@jgclark @EduardMe Look forward to comments

### CODE REVIEW

**Comment by EduardMe** [comment]
I think @dwertheimer, "indent" values are only available on tasks and bullets because these are the only items where you can indent the full paragraph. Plain text, headings, etc are not 'indentable' like tasks. You only get the first line indented. There is a discussion on Discord about indenting all fully. Then it would make sense to set an indent level everywhere.

Let me know if this helps or if I mixed up something.

**Comment by dwertheimer** [comment]
Thx @EduardMe. When you get a moment, pls try out my PRs for the task sweeper and the sorter. 

Task sweeper sweeps the last #H1 over with an indented task. The sorter, by design, just sorts tasks and ignores text and titles.  So at some point, we should come up with a strategy for how to do the sorting when there are indents and titles. The base case is simple but let's say you sweep multiple indented tasks of differing priorities to today's note. They are all now under the #H1. But when you sort them, what should happen?

**Comment by EduardMe** [comment]
Thanks, will check it out. Generally, indented tasks should stay below
their parent task, but that's not easy to implement (searching for the
parent) and then to sort indented tasks only between the other indented
tasks under the same parent. Because there might be tasks which are further
indented into level 2, 3, etc. I wanted to code this somehow, but couldn't
figure out a simple way to get the relationships right.

**Comment by jgclark** [comment]
I've only checked which files have been updated (given the issues reported in #22). 
So not reviewed, or tested, but committing as requested.

**Pull request merged**
