### PR TITLE
Create Raindrop.io integration plugin

### PR DESCRIPTION
**Pull request by KimMachineGun**
This pr is about an unofficial Raindrop.io integration plugin for working with NotePlan3.
Let me know if you have any suggestions, improvements, bugs, etc.

### CODE REVIEW

**Comment by dwertheimer** [comment]
This is cool, @KimMachineGun. Welcome to NP Plugin Dev! I glanced at the code and it looks great to me. My vsCode is not showing lint, Flow and formatting properly though. Hoping that @jgclark can have a quick look and push/release it.

**Comment by jgclark** [comment]
Oh, sorry, @KimMachineGun, I hadn't spotted this request, as I think I was ill at the time. Do you still want us to look at it, beyond what @dwertheimer has already said?

**Comment by dwertheimer** [comment]
@KimMachineGun I did not see any response from you to @jgclark's question. Are you still using NotePlan and this plugin? Another user is looking for it.

**Comment by dwertheimer** [comment]
@KimMachineGun A user had this feedback on the plugin: https://discord.com/channels/763107030223290449/1116134281295712286/1116183630667063326

> It is working great! This works better then the Logseq plug-in. Both commands are working, insert link and note creation. The only thing I noticed is that RD tags did not get inserted when the note command was run.

**Comment by KimMachineGun** [comment]
@dwertheimer @jgclark  
Oh.. sorry, I missed that comment.
Sadly, I'm no longer using NP actively anymore, and I would like to transfer the ownership of this plugin if possible. 😢

**Pull request merged**
