### PR TITLE
chore: update dependencies safely

### PR DESCRIPTION
**Pull request by nmn**
Updating some of the dependencies. For now I have not updated by major version to avoid any breaking changes.

### CODE REVIEW

**Comment by nmn** [comment]
@jgclark No, I'm not using `react-loader-spinner`. We can remove the dep if no one is using it. Will do.

**Comment by dwertheimer** [comment]
> @jgclark No, I'm not using `react-loader-spinner`. We can remove the dep if no one is using it. Will do.

@jgclark I think I was using it at one point on a project but I went another direction, so @nmn I'm good with you deleting it.

@nmn It's been several years, so I think we might need to bite the bullet and upgrade major versions also and figure out what we need to fix.

**Comment by dwertheimer** [comment]
@jgclark Also the tests that are failing are the ones we have fixed in the branch we've been working on. What would you think of doing a squash/merge into main of that branch so we can get the tests back to passing.

**Comment by nmn** [comment]
@dwertheimer which branch did you fix the tests in? I can just rebase this branch to merge into that one.

**Comment by dwertheimer** [comment]
@nmn The branch we have been working in is called "main-perspectives-merge-with-debug"

**Comment by nmn** [comment]
`npm test` now passes locally for me. All the tests that were failing are tests that should be disabled.

**Comment by nmn** [comment]
@dwertheimer PR merged into your branch. Make sure you pull these changes as you continue to work on your branch. Hopefully this gets you far along enough to fix your problem.

**Comment by dwertheimer** [comment]
@nmn @jgclark Should we get on a  brief Zoom call today to discuss what we
can do to test and help? There are some nuances that I want to make sure
@nmn is aware of.

**Comment by aaronpoweruser** [comment]
@dwertheimer I have some time I'll join.

**Comment by dwertheimer** [comment]
Fantastic. Let’s see when @nmn wants to do it.

**Comment by nmn** [comment]
Sorry, I don't think I'll have time for a zoom this week. Carry on without me.

**Comment by dwertheimer** [comment]
@nmn No worries. We can wait until you have some time to discuss.

**Comment by nmn** [comment]
It might be weeks. I'll be traveling and just contributing when I have some time.

**Pull request merged**
