### PR TITLE
created helper/timeblocks and tests from @jgclark's EventHelpers

### PR DESCRIPTION
**Pull request by dwertheimer**
Pushing this code to main so that @jgclark can continue with it

### CODE REVIEW

**Review by jgclark — COMMENTED** [review]
Thanks, David.

**Comment by mikeerickson** [comment]
@dwertheimer awesome! 

And I LOVE to see accompanying tests, makes it a complete submission.  

Thank you!

**Comment by mikeerickson** [comment]
When I do the next main update, it will have an updated README and will reference this as an example of how all future helpers should be arranged. @dwertheimer

**Comment by dwertheimer** [comment]
Nice!

**Pull request merged**
