### PR TITLE
dev.js fix

### PR DESCRIPTION
**Pull request by m1well**

### CODE REVIEW

**Comment by mikeerickson** [comment]
Why have you renamed the `environment` to `Environment` ?

**Comment by m1well** [comment]
> Why have you renamed the `environment` to `Environment` ?  

Because it is `Environment.environment` if you look at flow-typed. I dont know why, that is not from me. But it is the same like `Editor.xxx` or `DataStore.xx`

**Comment by mikeerickson** [comment]
Ah, I see what you mean there.   IMHO, I think it would be better to rename `Environment` to `NotePlan` 

My thinking there is, future “global” methods could be added which are not Environment type methods. I have proposed to @EduardMe to creature a new module `NotePlan` where he can add `environment` and future methods.

This PR will wait until @EduardMe has made his final decision as to where to place these “global” methods.

**Comment by m1well** [comment]
> Ah, I see what you mean there.   IMHO, I think it would be better to rename `Environment` to `NotePlan` 
> 
> 
> 
> My thinking there is, future “global” methods could be added which are not Environment type methods. I have proposed to @EduardMe to creature a new module `NotePlan` where he can add `environment` and future methods.
> 
> 
> 
> This PR will wait until @EduardMe has made his final decision as to where to place these “global” methods.

But the current code is also wrong. And with this PR we at least avoid the errors

**Comment by dwertheimer** [comment]
Closing this PR because: (a) the understanding of Environment is not correct (the comments are helpful to @EduardMe though) and (b) it rolls back some of the changes that @jgclark made and should persist.

**Pull request closed without merging**
