### PR TITLE
eventhelpers eventlist show calendarname

### PR DESCRIPTION
**Pull request by m1well**
* since I do not know which files are all affected on the new templating system from @mikeerickson, the only thing I can do is to bring up my ideas - if you don't merge them then it's a pity but ok
* because I also see the calendar of my wife, it would be nice to have the possibility to see the calendar name in the eventslist
* also I added a mapping, so that you can map the calendar name, maybe for formatting purposes (as it is for me)

### CODE REVIEW

**Comment by mikeerickson** [comment]
All these changes will have no impact on what is being done in the new templating plugin, thus they are safe to change.  I am going to leave this to @jgclark for his review as he knows the inner workings of this plugin.

**Review by jgclark — COMMENTED** [review]
Two comments on this:
1. Why have you introduced the `pref_showCalendarName`, as I can't see a purpose for it? Surely we can leave it to whether the template includes `*|CAL|*` or not?

2. Several times in the templates and settings you have `...*|CAL|**|TITLE|*...`. Won't these two need a space between them?

**Comment by m1well** [comment]
> Two comments on this:
> 
> 1. Why have you introduced the `pref_showCalendarName`, as I can't see a purpose for it? Surely we can leave it to whether the template includes `*|CAL|*` or not?
> 2. Several times in the templates and settings you have `...*|CAL|**|TITLE|*...`. Won't these two need a space between them?

to 1.:
it is used in the method `getReplacements` where all String "regex" are getting replaced:
 `value: pref_showCalendarName ? calendarNameWithMapping(item.calendar, pref_calendarNameMappings) : ''`
 
 to 2.:
yes I wanted to have a space between `CAL` and `TITLE` - but the problem is: because it is the first element.  
if you don't want to see the calendar name, then you have an empty space in front of your text.
example (white spaces are underlines to have a better look)
normal line:
`* hello_world`
line with CAL:
`* calname:_hello_world`
without cal:
`* _hello_world`

**Comment by jgclark** [comment]
> to 1.: it is used in the method `getReplacements` where all String "regex" are getting replaced: `value: pref_showCalendarName ? calendarNameWithMapping(item.calendar, pref_calendarNameMappings) : ''`

I understand how you've used it, but I was asking why you need it at all. It looks to me like you don't need this setting at all.
 
> to 2.: yes I wanted to have a space between `CAL` and `TITLE` - but the problem is: because it is the first element. if you don't want to see the calendar name, then you have an empty space in front of your text. 

Ah, yes, I see. Perhaps one way around this is once the whole line is constructed is to then run a replace that replaces any consecutive whitespace characters with a single space. I.e. \\h{2,} → \\s

**Comment by m1well** [comment]
> > to 1.: it is used in the method `getReplacements` where all String "regex" are getting replaced: `value: pref_showCalendarName ? calendarNameWithMapping(item.calendar, pref_calendarNameMappings) : ''`
> 
> I understand how you've used it, but I was asking _why you need it_. It still looks to me like you don't need this setting at all.
> 
> > to 2.: yes I wanted to have a space between `CAL` and `TITLE` - but the problem is: because it is the first element. if you don't want to see the calendar name, then you have an empty space in front of your text.
> 
> Ah, yes, I see. Perhaps one way around this is once the whole line is constructed is to then run a replace that replaces any consecutive whitespace characters with a single space. I.e. \h{2,} → \s


now I understood -> you are right - this boolean value is not needed because one could handle this via the `|CAL|` in the template string. I removed it.
also I added this replacement of multiple spaces with one.
but now because this boolean value is no longer needed - there is no case for this two spaces. but I added it anyway ;)

**Review by jgclark — APPROVED** [review]
I can see a line that needs removing still in timeblocks.js but I'm going to approve and sort it out from here to save time.

**Pull request merged**
