### PR TITLE
refactor: updated some jsdoc

### PR DESCRIPTION
**Pull request by m1well**
as discussed earlier - a separate pull request for "refactor: updated some jsdoc"

### CODE REVIEW

**Comment by dwertheimer** [comment]
Thanks for doing these PRs. Mike E is going to be out for a few days, so if nothing happens on the PRs, don't think you're being ignored. This is all helpful clean-up. Thanks for pitching in. I'm sure Mike will get to the PRs in a bit of time (it's Thanksgiving week here in the USA)

**Comment by mikeerickson** [comment]
@dwertheimer @jgclark Will any of these changes affect what you are doing to these helpers?  If not, I am thinking we should wait until after `np.Templating` and other plugin changes coming soon.  Further, I have a project `np.Documentation` in the works which could affect `jsdoc` blocks to a greater extent, so we will review it again at later date.

**Review by jgclark — APPROVED** [review]
Thanks. I'd suggest committing this now, as it'll be easier sooner rather than later. It tidies and corrects useful things, which should make any future jsdoc migration easier.

**Comment by dwertheimer** [comment]
These are great edits. Did you notice all this yourself or did IntelliJ/Lint point it out? Feels like you're seeing a lot of stuff!

**Pull request merged**
