### PR TITLE
Sweep Streamline (one file)/Extend (/sw7)

### PR DESCRIPTION
**Pull request by dwertheimer**
@nmn I made a lot of edits and clarifications. Todos in Project Notes weren't sweeping properly, so I dug in and decided to streamline the code, combining the Calendar Note and Project Note processing into one file, since it's 90% the same.  @EduardMe and @nmn Please try it out and see if it still works properly for you. I tested it out extensively, and everything works for me. 

- Fixed project note sweeping so tasks copy from project notes
- Combined Calendar and Notes processing into one file for consistency 
- Added /sw7 command to silently sweep notes from the last 7 days (sweep7() in sweepAll.js)
- Added comments for understanding the indents logic and console.logging
- Edited messaging for clarity for user
- Started fleshing out README

### CODE REVIEW

**Comment by dwertheimer** [comment]
@nmn Yes, I think we roll back minification, because, among other things, it seems to be causing merge conflicts. There were no conflicts when I made the PR, but when someone pushed something to main thereafter, the minified files show up as merge conflicts. See above. None of them are related to code in this branch. 

Can you or @jgclark please merge these PRs and close them? Thanks.

**Comment by jgclark** [comment]
I think there are 2 different issues here.  When working on merging @sidedwards' changes to Templates yesterday, it was causing necessary changes to several other plugins that use Templates/src files. But when `autowatch` starts up, it seems to re-compile **all** plugins, whether the code has changed or not. I don't fully understand what's going on in the rollup code, but it seems that's not a problem due to minify itself, but in the wider autowatch logic.

So my related request is for either or both of the following, @nmn :
1. Adjust `npm run autowatch` to only run for a plugin when its src files have changed.
2. Bring back the `npm run build:<plugin>` command, so I can just work on one plugin without disturbing others.
(And, either way, the README needs updating.)

**Comment by jgclark** [comment]
> Can you or @jgclark please merge these PRs and close them? Thanks.

You've got 34 changed files here -- a result (I think) of what I've described above, with autowatch recompiling all the plugins. What I will attempt to do is only check in the actual sweep-related files. If I can't manage that, then I'll check them all in, though it might make the history a little confusing.

**Comment by nmn** [comment]
> 1. Adjust npm run autowatch to only run for a plugin when its src files have changed.
> 2. Bring back the npm run build:<plugin> command, so I can just work on one plugin without disturbing others.
(And, either way, the README needs updating.)

regarding this, I think we cam just make `npm run auto watch` better by letting it ask for options. It can let you choose a subset of plugins that should be compiled and watched. That way we don’t need the individual roll up configs that can be error prone.

**Comment by nmn** [comment]
There are a lot of changes here that are undoing changes made to the main branch. I believe you need to rebase this PR.

**Comment by nmn** [comment]
Since you’ve closed it I’ll try to pick up and redo your changes.

**Comment by dwertheimer** [comment]
Thanks for trying @nmn and @jgclark. I am not enough of a Git guru to weather this storm, so I closed the PR and will leave it to @nmn. @nmn pls let me know if you want me to send any of the code I wrote. When I opened the PR, there were no conflicts. So whatever got pushed thereafter caused some issues. This happened to me twice before because as my PRs sat open, code alonside was being re-written. Beyond the rollup issues, I think part of the challenge here is that everybody is (essentially) writing the entire repo. Is there not a way that we can add our own pieces and control them without having to even worry about what's happening in all the other folders? I guess this maybe brings us back to the npm conversation?

**Comment by jgclark** [comment]
>
> When I opened the PR, there were no conflicts. So whatever got pushed
> thereafter caused some issues. This happened to me twice before because as
> my PRs sat open, code alonside was being re-written. Beyond the rollup
> issues, I think part of the challenge here is that everybody is
> (essentially) writing the entire repo. Is there not a way that we can add
> our own pieces and control them without having to even worry about what's
> happening in all the other folders? I guess this maybe brings us back to
> the npm conversation?
>
I don't know what the "npm solution" really means in practice for both devs
and users, so can't comment.
I think you've been unfortunate in coinciding with what was effectively a
change to the dev architecture itself (move to single builder + minify),
which triggered changes in every plugin.
I'm trying to get in the habit of making any changes to shared resources
(mostly = nmn.Templates) in a branch in a PR, so it can be assessed by
others, and backed out more easily. But any changes to just one of my own
plugins I do directly into main.  As ever I'm happy to be guided by people
with more Git experience.

**Pull request closed without merging**
